version: "3.3"
services:
  app:
    build:
      context: ./app
    ports:
      - 8080:80
    depends_on:
      - db
  db:
    image: mysql:5
    ports:
      - 3306:3306
    volumes:
      # Store data in Host file system
      - ./db/data:/var/lib/mysql
      # Restore db from dump
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: example

